# Generated by Django 5.0.6 on 2024-07-07 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CalidadAire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('real_pm25', models.FloatField()),
                ('predicted_pm25', models.FloatField()),
            ],
        ),
    ]
